### ISSUE TITLE
00 序文 のアップデート

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/edition-guide#23]
「序文」の内容を最新版にアップデートする。

差分は [mdbook-transcheck](https://qiita.com/dalance/items/ffed536c7d76897950c3) で確認する。

- 対象ファイル：masterブランチの [src/introduction.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/introduction.md)

----

翻訳手順について、まだドキュメント化できていません。Slack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 やります

**Comment by tatsuya6502** [comment]
@TonalidadeHidrica アサインしました
