### ISSUE TITLE
01-01 新しいプロジェクトを作成する のアップデート

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/edition-guide#25]
「新しいプロジェクトを作成する」の内容を最新版にアップデートする。

差分は [mdbook-transcheck](https://qiita.com/dalance/items/ffed536c7d76897950c3) で確認する。

- 対象ファイル：masterブランチの [src/editions/creating-a-new-project.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/editions/creating-a-new-project.md)

----

翻訳手順について、まだドキュメント化できていません。Slack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 やります

**Comment by tatsuya6502** [comment]
@TonalidadeHidrica アサインしました。よろしくお願いします。
