### ISSUE TITLE
01-02 既存のプロジェクトのエディションを移行する のアップデート

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/edition-guide#26]
「既存のプロジェクトのエディションを移行する」の内容を最新版にアップデートする。

差分は [mdbook-transcheck](https://qiita.com/dalance/items/ffed536c7d76897950c3) で確認する。

- 対象ファイル：masterブランチの [src/editions/transitioning-an-existing-project-to-a-new-edition.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/editions/transitioning-an-existing-project-to-a-new-edition.md)

----

翻訳手順について、まだドキュメント化できていません。Slack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 やります

**Comment by tatsuya6502** [comment]
@TonalidadeHidrica アサインしました。よろしくお願いします。
