### ISSUE TITLE
02 Rust 2015 のアップデート

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/edition-guide#27]
「Rust 2015」の内容を最新版にアップデートする。

差分は [mdbook-transcheck](https://qiita.com/dalance/items/ffed536c7d76897950c3) で確認する。

- 対象ファイル：masterブランチの [src/rust-2015/index.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/rust-2015/index.md)

----

翻訳手順について、まだドキュメント化できていません。Slack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 手元で確認したところ、差分はないようでした。

**Comment by tatsuya6502** [comment]
@TonalidadeHidrica あ、そうでしたか。当方の確認不足ですみません。

ではこのファイルは翻訳済みとします。
