### ISSUE TITLE
04 Rust 2021 の新規翻訳

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/edition-guide#28]
「Rust 2021」の内容を新規に翻訳する。原文は [mdbook-transcheck](https://qiita.com/dalance/items/ffed536c7d76897950c3) が処理できる形式でコメントアウトする。

- 対象ファイル：masterブランチの [src/rust-2021/index.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/rust-2021/index.md)

----

翻訳手順について、まだドキュメント化できていません。Slack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 やります

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 

[ここの部分](https://github.com/rust-lang-ja/edition-guide/blob/master/src/rust-2021/index.md?plain=1#L3-L6) って訳すんでしたっけ？

**Comment by tatsuya6502** [comment]
@TonalidadeHidrica アサインしました

**Comment by tatsuya6502** [comment]
> [ここの部分](https://github.com/rust-lang-ja/edition-guide/blob/master/src/rust-2021/index.md?plain=1#L3-L6) って訳すんでしたっけ？

@TonalidadeHidrica — テーブルですか。いままでなかったパターンかも。しかも [Rust 2018 の方](https://github.com/rust-lang-ja/edition-guide/blob/master/src/rust-2018/index.md) はテーブル内に文章が入ってますね。

Info と Release version は訳しましょう。（RFC はそのままで）

**Comment by TonalidadeHidrica** [comment]
@tatsuya6502 ありがとうございます。そのように修正しました。
